release notes & changelog practices suggestions
City-of-Helsinki/bestpractice pull request #16
Opened 2020-04-15 13:35 UTC by petterill

Suggestions about adhering to Keep a Changelog https://keepachangelog.com/en/1.0.0/ when doing releases. Some projects already utilize this format at Kuva and Kanslia.

2020-04-16 18:29 UTC, tituomin commented
This needs discussion. It's better to pick one way of doing this instead of saying "changelog or github release notes". The two are incompatible:  

> GitHub Releases create a non-portable changelog that can only be displayed to users within the context of GitHub. It's possible to make them look very much like the Keep a Changelog format, but it tends to be a bit more involved.
>
> The current version of GitHub releases is also arguably not very discoverable by end-users, unlike the typical uppercase files (README, CONTRIBUTING, etc.). Another minor issue is that the interface doesn't currently offer links to commit logs between each release.

2020-04-16 18:30 UTC, tituomin requested changes
Needs one recommended way. We need to talk about it more.

2020-04-17 05:41 UTC, petterill commented
Yes I agree, would be better to suggest only one way of doing things. @pkalliok comments?

2020-04-27 10:39 UTC, Jokinen commented
As further context, of the example projects presented here, all but respa use both a changelog and a release. The release notes are just the content of the changelog for that version.

2020-05-26 20:23 UTC, pkalliok approved these changes
It's almost irrelevant what it is, as long as we stick to one.  I don't like the keepachangelog format and prefer debian changelog (https://manpages.debian.org/testing/dpkg-dev/deb-changelog.5.en.html), but truth be told, keepachangelog is as good as any.

2020-05-26 20:23 UTC, pkalliok commented on version-control.md
> +* Document changes in a changelog or in Github release notes. [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) offers a good model for informing users about changes in a release.
```suggestion
* Document changes in a changelog that is called `CHANGELOG.md` and resides at the root of your repository. [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) offers a good model for informing users about changes in a release.
```

2020-06-01 14:13 UTC, petterill commented
Since the file was moved, I'll create another PR for this small change. Solving git conflicts is confusing...

2020-06-01 14:13 UTC, closed without merging