Migrate authentication docs from Confluence
City-of-Helsinki/bestpractice pull request #28
Opened 2020-04-29 10:13 UTC by vikoivun

## Description :sparkles:

Adds description of the tools used for authentication. Currently rather low level.

2020-05-13 11:58 UTC, vikoivun commented
Now with introductory text!

2020-05-13 13:11 UTC, petterill reviewed
Looks good to me. Just some stylistic suggestions.

2020-05-13 13:11 UTC, petterill commented on docs/authentication.md
> +Tunnistamo is service that authenticates users against several different identity sources,
```suggestion
Tunnistamo is a service that authenticates users against several different identity sources,
```

2020-05-13 13:11 UTC, petterill commented on docs/authentication.md
> +To get started you will either need a locally setup instance of Tunnistamo or get access to one of shared instances available within Helsinki infrastructure. I'd recommend that you try and get access
```suggestion
To get started you will either need a locally setup instance of Tunnistamo or get access to one of shared instances available within Helsinki infrastructure. It is recommended that you try and get access to the shared instances, unless you must develop offline. 
```

2020-05-13 13:11 UTC, petterill commented on docs/authentication.md
> +To get access to Kanslia instance, pop by the slack channel #tunnistamo
```suggestion
To get access to Kanslia instance, pop by the slack channel #tunnistamo.
```

2020-05-14 10:51 UTC, petterill requested changes
Forgot to add that the metadata must be added for the doc to show up on the site correctly

2020-05-14 10:51 UTC, petterill commented on docs/authentication.md
> +# Authentication
```suggestion
---
name: Authentication
menu: Best practices
route: /authentication
---

# Authentication
```

2020-05-14 10:58 UTC, petterill approved these changes

2020-05-14 10:59 UTC, merged